apiVersion: v1
kind: Service
metadata:
  name: memory-hog
  namespace: safeheal-demo
spec:
  selector:
    app: memory-hog
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
